### ISSUE TITLE
Hallo

### ISSUE THREAD

**Issue by maartenvda** [Arnobw/eentcoin#1]
//

**Comment by maartenvda** [comment]
oopsie agressieve eent kwam binnengewandeld ik heb moeten vechten voor mijn leven en ben vergeten wat ik nog wou zeggen geen zorgen ik heb dit niet geleakt dit is gewoon de enige manier van communiceren want geen fb

**Comment by Arnobw** [comment]
Oh juist, da's waar. Niet dat ik iemand echt heb zien kijken, en anders mogen ze me wel een job geven hoor

**Comment by maartenvda** [comment]
Kans is zeer groot dat niemand dat gezien heeft hoor
Veel plezier nog met de pagina, ik check af en toe nog eens voor de nostalgic vibes
Groetjes analyticus
